# Generated by Django 3.1.5 on 2021-01-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production',
            field=models.CharField(default='', max_length=50),
        ),
    ]
