# Generated by Django 3.1 on 2021-01-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production',
        ),
    ]
