# Generated by Django 3.1.5 on 2021-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('proccessing', 'Processing'), ('in_delievery', 'In delievery'), ('finished', 'Finished'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
